### 1.빅데이터 분석 및 처리

#### 빅데이터

- 기존의 전통적 데이터 관리 기법으로 데이터의 수집이나 저장, 분석 등을 다루기 어려운 정형 및 비정형 데이터

#### R

- 통계 계산과 그래픽을 위한 프로그래밍 언어이자 소프트웨어 환경

#### python

- 연산능력을 극대화 시켜주는 오프소스 라이브러리가 풍부
- 높은 접근성, 대용량 데이터 처리에 유연성을 가짐
- 다양한 패키지가 목적에 맞게 개발

### 2.데이터 저장 및 가공

#### 데이터 분석

- 숫자 배열을 효율적으로 저장하고 가공하는 것은 빅데이터 분석을 위한 기본 절차
- 숫자 배열을 전문적으로 다루는 Numpy 패키지 제공

### 3.Numpy 패키지

#### 넘파이(Numerical Python)

- 벡터 및 행렬 연산에 유용한 기능 제공
- 빅데이터 분석 및 처리를 위해 사용되는 라이브러리
(pandas와 matplotlib에서 기본으로 사용)
- array(동일한 데이터 타입을 갖는 벡터나 행렬) 단위로 사용

### 4.행렬 생성

In [1]:
import numpy as np

data1 = [1,2,3,4,5]
data2 = [6,5,4,3,2,1]
print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [2]:
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

In [3]:
ar2 = np.array(data1, dtype = 'float')
ar2

array([1., 2., 3., 4., 5.])

In [4]:
ar3 = np.array([range(i, i+3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [5]:
ar4 = np.full((3,5),3.14)
ar4

# .full ((행렬의 크기), 지정 값)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
ar6 = np.linspace(0, 1, 3)
ar6

# 0.5 간격의 3가지 요소 배열

array([0. , 0.5, 1. ])

In [12]:
ar7 = np.random.random((3,3))
ar7

# 3x3 행렬을 생성, 0과 1 사이의 랜덤 값으로 채움

array([[0.71952495, 0.68838003, 0.5709802 ],
       [0.69350026, 0.90606211, 0.19579569],
       [0.32878231, 0.25842921, 0.59086348]])

In [13]:
ar8 = np.random.randint(0, 100, (3,3))
ar8

# 0과 100 사이 (구간의 시작, 구간의 끝)
# 3x3 배열크기

array([[13, 15, 77],
       [27, 51, 31],
       [11, 69, 57]])

In [10]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 5.배열 분할, 재구성, 결합

In [14]:
x = np.random.randint(10, size=(3,4,5))
x

array([[[2, 8, 6, 1, 0],
        [0, 2, 5, 6, 7],
        [6, 2, 4, 9, 7],
        [7, 6, 2, 8, 2]],

       [[1, 7, 0, 0, 0],
        [0, 9, 5, 9, 1],
        [5, 5, 4, 8, 6],
        [3, 8, 0, 1, 8]],

       [[5, 9, 9, 3, 5],
        [5, 6, 9, 2, 6],
        [4, 8, 4, 2, 4],
        [6, 1, 7, 5, 0]]])

In [19]:
print("x ndim:", x.ndim) #차원의 개수
print("x shape:", x.shape) #차원의 크기
print("x size:", x.size) #전체 배열 크기

x ndim: 3
x shape: (3, 4, 5)
x size: 60


In [16]:
y = np.array([2,4,6,8,10])
print(y[0], y[-2])

2 8


In [17]:
z = np.array([[2,4,6,8,10], [3,6,9,12,15]])
print(z[1,0])

3


In [18]:
z[0,0] = 12
z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])